### ISSUE TITLE
bug with inference when working with multiple GPUs

### ISSUE THREAD

**Issue by michalhg** [Project-MONAI/MONAI#1377] opened 2020-12-17 10:16 UTC
I received this error : 
seg_prob = predictor(window_data, *args, **kwargs).to(device)  # batched patch segmentation
AttributeError: 'tuple' object has no attribute 'to'

the network I ran is SegResnetVAE, on two GPUs,  using DataParallel for the model.

I don't understand this error

**Comment by wyli** [comment] 2020-12-17 11:55
looks like duplicate of https://github.com/Project-MONAI/MONAI/issues/1263 the network returns a tuple instead of tensor. so  could try using `lambda image: segresnet(image)[0]` as the model to sliding window

**Comment by Nic-Ma** [comment] 2020-12-18 23:20
close as duplicated issue.
Thanks.

**Closed by Nic-Ma** 2020-12-18 23:20 UTC
