### ISSUE TITLE
Spatial transforms / RandAffined/ Resampler should not change data type

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5511] opened 2022-11-10 23:10 UTC
Spatial transforms are internally changing the input data type , e.g. for RandAffined and RandAffine. 
A typical random tranform `RandAffined(keys=['image', 'label'], mode=['bilinear', 'nearest'])` where label (potentially uint8 type) only needs nearest neighbor interpolation, but will be converted to float32 or even float64 and will take more memory (and incurs an extra memory copy)

https://github.com/Project-MONAI/MONAI/blob/8b1f0c35326d162d30ebb72827ba06b65065bf3e/monai/transforms/spatial/array.py#L2523-L2530

If we do not do this random transform (skipping due to probability), then the data type is always converted to `torch.float32` in `convert_data_type(img, dtype=torch.float32` 

If we do apply this transform then `self.resampler` will internally converts this to float64 (and there is no way to change it, since this is the default)

https://github.com/Project-MONAI/MONAI/blob/8b1f0c35326d162d30ebb72827ba06b65065bf3e/monai/transforms/spatial/array.py#L2003-L2010

The Resampler() class should probably have the default dtype=None (not float64)

Finally at the end of Resampler call, the data is converted yet again from float64 -> float32 

https://github.com/Project-MONAI/MONAI/blob/8b1f0c35326d162d30ebb72827ba06b65065bf3e/monai/transforms/spatial/array.py#L2153-L2154

Similar situation for RandRotate, RandZoom, possible other transforms.

I suggest, we

- preserve the input data type, and output the same data type
- don't do internal data conversions (unless it's really necessary)

(this will help reduce memory pressure, and increase speed)

**Comment by wyli** [comment] 2022-11-10 23:23
Perhaps a duplicate of https://github.com/Project-MONAI/MONAI/issues/3831 the backend doesn't support different styles.

**Comment by vikashg** [comment] 2024-01-05 14:46
closing because there is a duplicate

**Closed by vikashg** 2024-01-05 14:46 UTC
Labels: bug
