### ISSUE TITLE
Potential circular import

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#1691] opened 2021-03-04 16:23 UTC
**Describe the bug**

**To Reproduce**
1. Go to `image_reader.py` (https://github.com/Project-MONAI/MONAI/blob/380f042dec9c55ba1a5ab241ae6b1a7b3e2b07fb/monai/data/image_reader.py)
2. Add a transform from op, post, spatial, transform, utility, or utils to the file, for instance `from monai.transforms import EnsureChannelFirst`
3. Run any test, for instance `python tests/test_ensure_channel_first.py`

**Expected behavior**
```
ImportError: cannot import name 'EnsureChannelFirst' from partially initialized module 'monai.transforms' (most likely due to a circular import) (/workspace/MONAI/monai/transforms/__init__.py)
```

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Comment by behxyz** [comment] 2021-03-04 16:23
@wyli @Nic-Ma, any thought?

**Comment by rijobro** [comment] 2021-03-04 16:39
The error is normally a bit longer than that isn't it? Sometimes it helps narrow down where the circular import is coming from. 

At any rate, I guess the problem is that you're trying to import `monai.transforms` in `monai.data`, but `monai.transforms` already imports `monai.data` (e.g., https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/io/array.py#L22).

**Comment by rijobro** [comment] 2021-03-04 16:46
(My understanding is that this problem would go away if throughout the MONAI codebase we imported modules rather than importing **from** modules, but that would be a huge amount of work!)

**Comment by wyli** [comment] 2021-03-04 17:13
I think within the project we should use more accurate module names such as `from monai.transforms.utility.array import EnsureChannelFirst` instead of `from monai.transforms import EnsureChannelFirst`

**Comment by behxyz** [comment] 2021-03-04 17:25
> The error is normally a bit longer than that isn't it? Sometimes it helps narrow down where the circular import is coming from.
> 
> At any rate, I guess the problem is that you're trying to import `monai.transforms` in `monai.data`, but `monai.transforms` already imports `monai.data` (e.g., https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/io/array.py#L22).

Here is the traceback:
```
Traceback (most recent call last):
  File "tests/test_ensure_channel_first.py", line 22, in <module>
    from monai.data import ITKReader
  File "/workspace/MONAI/monai/__init__.py", line 43, in <module>
    load_submodules(sys.modules[__name__], False, exclude_pattern=excludes)
  File "/workspace/MONAI/monai/utils/module.py", line 75, in load_submodules
    mod = import_module(name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/MONAI/monai/apps/__init__.py", line 12, in <module>
    from .datasets import CrossValidation, DecathlonDataset, MedNISTDataset
  File "/workspace/MONAI/monai/apps/datasets.py", line 19, in <module>
    from monai.data import (
  File "/workspace/MONAI/monai/data/__init__.py", line 14, in <module>
    from .dataset import (
  File "/workspace/MONAI/monai/data/dataset.py", line 28, in <module>
    from monai.transforms import Compose, Randomizable, Transform, apply_transform
  File "/workspace/MONAI/monai/transforms/__init__.py", line 141, in <module>
    from .io.array import LoadImage, SaveImage
  File "/workspace/MONAI/monai/transforms/io/array.py", line 22, in <module>
    from monai.data.image_reader import ImageReader, ITKReader, NibabelReader, NumpyReader, PILReader
  File "/workspace/MONAI/monai/data/image_reader.py", line 23, in <module>
    from monai.transforms import EnsureChannelFirst
ImportError: cannot import name 'EnsureChannelFirst' from partially initialized module 'monai.transforms' (most likely due to a circular import) (/workspace/MONAI/monai/transforms/__init__.py)
```

Yes, that's one of the circular imports.

**Comment by behxyz** [comment] 2021-03-04 17:28
> I think within the project we should use more accurate module names such as `from monai.transforms.utility.array import EnsureChannelFirst` instead of `from monai.transforms import EnsureChannelFirst`

Agree, this is how I am already using now to circumvent the issue but probably it's the best to enforce it in our code reviews because I see it throughout MONAI.

**Comment by wyli** [comment] 2021-03-05 10:28
thanks, as the codebase grows, to fully address this issue we'll need to reorganise some of the modules...but for now we could discuss case by case in the PRs. closing this but please feel free to reopen

**Closed by wyli** 2021-03-05 10:28 UTC
