### ISSUE TITLE
3D or multi-dimensional version of TORCHVISION.OPS

### ISSUE THREAD

**Issue by cckao** [Project-MONAI/MONAI#1551] opened 2021-02-05 09:44 UTC
Hi,

The operations in https://pytorch.org/docs/stable/torchvision/ops.html are useful but they only work under 2D contexts. Do you think it's reasonable to implement a 3D version in MONAI?

Thanks a lot.

**Comment by wyli** [comment] 2021-02-05 13:02
duplicate of https://github.com/Project-MONAI/MONAI/issues/1205  I'm closing this one. (any updates? @pfjaeger @mibaumgartner)

**Closed by wyli** 2021-02-05 13:02 UTC
