### ISSUE TITLE
WSIReader, cucim , tifffile, performance regressions

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5580] opened 2022-11-24 22:30 UTC
with pathology MIL classification tutorial, as an example
https://github.com/Project-MONAI/tutorials/blob/main/pathology/multiple_instance_learning/panda_mil_train_evaluate_pytorch_gpu.py

WSIReader is now imported from  `from monai.data.wsi_reader import WSIReader`. If changing the import to the old way (now deprecated)  `from monai.data.image_reader import WSIReader`, and setting backend=tifffile, then training is ~10% faster.  seems like a performance regression.

Training time on 8gpu, 1 epoch
- from monai.data.wsi_reader import WSIReader, (backend=cucim)   313 seconds
- from monai.data.wsi_reader import WSIReader, (backend=tiffile)   303 seconds
- from monai.data.image_reader import WSIReader, (backend=tiffile)   283 seconds

**Comment by drbeh** [comment] 2023-03-01 21:37
Hi @myron, thank you very much for reporting this. I have investigated this issue and realized that the root cause is an "unnecessary" array copy in the `wsi_reader.WSIReader`. After fixing this, `wsi_reader.WSIReader` seems to be faster than `image_reader.WSIReader` (see blow). I will submit the PR momentarily. It would be great if you can check the run time of MIL tutorial after the PR is merged. Thanks

```python
from monai.data.wsi_reader import WSIReader
from monai.data.image_reader import WSIReader as WSIReader2

filename = "temp_CMU-1.tiff"
reader1 = WSIReader(backend="TiffFile")
reader2 = WSIReader2(backend="TiffFile")
obj1 = reader1.read(filename)
obj2 = reader2.read(filename)
```
```python
%%timeit
reader1.get_data(obj1, level=1)
```
current performance: 2.32 s ± 97.7
after fixing the issue: 1.45 s ± 12.9 ms

```python
%%timeit
reader2.get_data(obj2, level=1)
```
current performance:  1.97 s ± 50.2 ms
after fixing the issue:. 1.93 s ± 141 ms

**Closed** 2023-03-02 13:03 UTC
Labels: Pathology/Microscopy

**Comment by myron** [comment] 2023-03-02 23:15
okay, there was a very short time window for me to test it before merging. but since it's already merged, I'll just test it a bit later, when I get to it.  But thank you for debugging and fixing it!
