### ISSUE TITLE
Invalid shape sample from RandCropByLabelClasses

### ISSUE THREAD

**Issue by ltetrel** [Project-MONAI/MONAI#7254] opened 2023-11-23 10:22 UTC
**Describe the bug**
I was running `Auto3dseg` and the train transform failed when creating the batch (collate the samples), because few did not match the patch size I defined (one had `(96, 95, 96)` when others had `(96, 96, 96)`).

It seems that the culprit was actually `RandCropByLabelClasses`. When generating its [random sample centers](https://github.com/Project-MONAI/MONAI/blob/8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b/monai/transforms/croppad/array.py#L1347C24-L1347C59), it will [correct them](https://github.com/Project-MONAI/MONAI/blob/8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b/monai/transforms/utils.py#L640) if they do not fall within the boundary of the label. However, if the image and label have different shape, the center are not correctly corrected because they use the size of the label, when it should use the size of the image (which we are actually cropping). As a result, the resulting sample are not correctly cropped and don't have the shape defined by [`spatial_size` parameter](https://github.com/Project-MONAI/MONAI/blob/8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b/monai/transforms/croppad/array.py#L1269).

Having different shapes can happen because of truncating error when using a nearest neighbor (for label) VS bilinear (for image) resampler.

I suppose the same issue could happen with `RandCropByPosNegLabel` ?

**To Reproduce**
Here is a code snippet to reproduce the issue

```
import numpy as np

from monai.config import print_config
from monai.utils import set_determinism
from monai.transforms import RandCropByLabelClasses
from monai.data.synthetic import create_test_image_3d


def main():
    seed = 9
    set_determinism(seed=seed)
    roi_size = (24, 24, 24)

    test_img, test_label = create_test_image_3d(height=100, width=100, depth=100, channel_dim=0)
    test_img = test_img[..., :-1, :-1, :]
    rand_cropper_by_label = RandCropByLabelClasses(num_classes=5, spatial_size=roi_size, warn=False, lazy=False)
    rand_cropper_by_label.set_random_state(seed=seed)
    rand_cropped_img = rand_cropper_by_label(img=test_img, label=test_label)

    np.testing.assert_equal(rand_cropped_img[0].shape[1:], roi_size)
    print(f"{rand_cropped_img[0].shape}")


if __name__ == '__main__':
    main()

```

**Expected behavior**
The above snipper should return
```
torch.Size([1, 24, 24, 24])
```

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0+untagged.2912.g8e134b8.dirty
Numpy version: 1.24.4
Pytorch version: 1.13.0a0+git49444c3
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b
MONAI __file__: /home/<username>/.venvs/monai-fix-crop-correction/src/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
scipy version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 7.0.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.15.0a0+01ef0a6
tqdm version: NOT INSTALLED or UNKNOWN VERSION.
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.6
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.
clearml version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.6 LTS
Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.29
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/ltetrel/.config/Code/logs/20231123T104957/ptyhost.log', fd=35, position=0, mode='a', flags=33793), popenfile(path='/snap/code/146/usr/share/code/resources/app/node_modules.asar', fd=38, position=55268, mode='r', flags=32768), popenfile(path='/snap/code/146/usr/share/code/v8_context_snapshot.bin', fd=103, position=0, mode='r', flags=32768)]
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [0.0, 3.2, 0.0, 0.0, 9.1, 56.7, 0.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 41.9, 0.0, 0.0]
CPU freq. (MHz): 2276
Load avg. in last 1, 5, 15 mins (%): [10.8, 10.4, 9.7]
Disk usage (%): 69.8
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.1
Available memory (GB): 23.4
Used memory (GB): 6.1

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.7
cuDNN enabled: True
NVIDIA_TF32_OVERRIDE: None
TORCH_ALLOW_TF32_CUBLAS_OVERRIDE: None
cuDNN version: 8600
Current device: 0
Library compiled for CUDA architectures: ['sm_86']
GPU 0 Name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 20
GPU 0 Total memory (GB): 3.8
GPU 0 CUDA capability (maj.min): 8.6
```

**Additional context**
I will make a PR with a tentative fix

**Comment by KumoLiu** [comment] 2023-11-23 10:47
Hi @ltetrel, perhaps you could add a `ResampleToMatch` to align the size and affine.
https://github.com/Project-MONAI/MONAI/blob/8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b/monai/transforms/spatial/array.py#L253

**Comment by ltetrel** [comment] 2023-11-23 10:54
thanks @KumoLiu 
I was indeed thinking to use this, but RandCropByLabelClasses should not use the label to correct its generated centers anyway to prevent this kind of issues.
Currently submitting a PR for this (local tests are running)

**Comment by KumoLiu** [comment] 2023-11-23 11:24
Personally feel image and label should be aligned in this transform since the generated centers were chosen by the label. If not, even if you use image size to correct the centers, the user may be unaware that their data may be incorrect (although the size mismatch here isn't a big issue in your case). Perhaps we should add a warning here when images and labels are not aligned, what do you think?
cc @ericspod

**Comment by ltetrel** [comment] 2023-11-23 12:01
I have a warning about this [here](https://github.com/Project-MONAI/MONAI/pull/7255/files#diff-96cd15307195a8d855e3fb33c35abaa18afaecc182874751af4eb3144726d158R621)
Regarding the current question about whether `RandCropByLabelClasses` should have same shape for label/image, it seems quite difficult to understand what should be done.
Again, this happen when using `Auto3DSeg`, an autoML pipeline that is expected to be used by non-devs.

Wether (1) we enforce same shape for image/label in `RandCropByLabelClasses`, or (2) take that into account in the transform.
(1) It can be either a simple warning, with the advantage of not breaking actual implementations. But with the risk of silent failing. If an error is raised, it is the opposite. Either way people will need to re-design their train transforms (which is actually not "easilly" do-able with Auto3dseg for ex).
(2) It is handled by the function which introduces "maintenance burden" and introduce complexity, and maybe a more complicated usage for the end user (actually in the current proposal, the changes are hidden by the end user).

**Comment by ericspod** [comment] 2023-11-23 14:27
We haven't seen this sort of issue before because we're usually able to preprocess data to ensure image and label sizes match. If the label is significantly than the image, should it be resized to match or padded to match (assuming it should be centred on the image)? Should the image be cropped instead to match the label? You can't really tell from image/label pairs which one it is so if you're defining your own transform sequence I'd have said to crop or pad as needed with ResizeWithPadOrCrop to get the two to match. I think the fix for `RandCropByLabelClasses` would work for the Auto3DSeg case and for everyone else whose images and labels match, but in general perhaps Auto3DSeg needs to do something itself a little more intelligent to detect this case.

**Comment by ericspod** [comment] 2023-11-23 14:29
CC @mingxin-zheng @Nic-Ma

**Comment by KumoLiu** [comment] 2023-11-24 03:40
I agree with the @ericspod, `Auto3DSeg` perhaps needs to do more enhancement to detect this issue.
@ltetrel, could you please explain in more detail why the image and label are mismatched in your case? Is this a common issue?
IMO, if the center is generated by the label, and yet at this point, the image you want to crop is way out of scale with the size of the label, that's weird, and we can certainly SLIENT the solution, but it's may not what the user wants. At least we should tell the user when the image and label are not the same shape.

**Comment by ltetrel** [comment] 2023-11-27 13:59
@KumoLiu 
If you look at the train transform [here](https://github.com/Project-MONAI/research-contributions/blob/0043502afc81978111d3da75350ab1ac28a416cb/auto3dseg/algorithm_templates/swinunetr/configs/transforms_train.yaml#L15C20-L19C29), you see that the interpolation method is different (`bilinear` vs `nearest`) for image and label.
As an effect and because there can be truncating error with nearest neighbor, the shape can also be different. Hence it fails after when doing data augmentation with [RandCropByLabelClassesd](https://github.com/Project-MONAI/research-contributions/blob/0043502afc81978111d3da75350ab1ac28a416cb/auto3dseg/algorithm_templates/swinunetr/configs/transforms_train.yaml#L35-L41).

I am not sure if this issue should be fixed in `Auto3dseg` , or this side case to be taken into account within `RandCropByLabelClassesd` (as proposed in the PR). Either way I think we agree there should be a warning at least.

**Comment by KumoLiu** [comment] 2023-11-29 08:26
Hi @ltetrel, if the mismatch is caused by the interpolation mode in other transforms, then perhaps we may take a look at them instead of using image shape as a workaround in `RandCropByLabelClassesd`?
When you use the img shape, the pipeline works, but because the center is generated from the unravel label, and because the image and the label are not the same shape, the generated center is not in the same place as the corresponding image, will it be expected?

**Comment by ltetrel** [comment] 2023-12-12 09:55
A little update on my side regarding my current issue (invalid shapes before [RandCropByLabelClassesd](https://github.com/Project-MONAI/research-contributions/blob/0043502afc81978111d3da75350ab1ac28a416cb/auto3dseg/algorithm_templates/swinunetr/configs/transforms_train.yaml#L35-L41) with Auto3DSeg).
I thought the shape mismatch was due to rounding error when using nearest neighbor vs bi-linear resampling (which did not really make sense afterall). Actually this is wrong, the real issue was that my input label vs image affines were (very) slightly off.

For this current PR, I think it still makes sense (raising a warning if invalid shapes, and maybe using img instead of label for crop centers correction). WDYT ?

**Comment by ericspod** [comment] 2023-12-12 14:36
Hi @ltetrel good to hear you've found the issue. I'm not sure if this issue would come up for others terribly much, and since it was something with your processing rather than an inherent problem with the transform we should get some feedback from others if they feel this change makes sense. @KumoLiu  @dongyang0122 @Nic-Ma @mingxin-zheng Thanks!

**Comment by vikashg** [comment] 2024-01-04 22:14
closing as to very specific narrow case. Reopen if help needed

**Closed by vikashg** 2024-01-04 22:14 UTC
Labels: enhancement, Design discussions
