### ISSUE TITLE
Training on dicom images throws key errors:  "0008|0005", "0008|1050" or similar

### ISSUE THREAD

**Issue by ChristianEschen** [Project-MONAI/MONAI#2948] opened 2021-09-14 12:04 UTC
Hi all

I have been facing some problems training on DICOM images. In specific I found that training throws key errors on "0008|0005", "0008|1050", which conditional optional and optional.

The files can be found here: 
http://www.rubomedical.com/dicom_files/dicom_viewer_0002.zip
http://www.rubomedical.com/dicom_files/dicom_viewer_0003.zip

My enviroment is:
Ubuntu 20.04 LTS
Monai: 0.7.dev2137 (I have also tested with master)

The code to reproduce the error is here:
(Removing the comment section with pydicom solves the issue since the metadata is updated to have the correct keys.)

```

import logging
import os
import sys

import numpy as np
import torch
from torch.utils.data import DataLoader
import monai
print('monai vers', monai.__version__)
import pydicom
from monai.transforms import Activations, AddChanneld, AsDiscrete, Compose, LoadImaged, RandRotate90d, Resized, ScaleIntensityd, EnsureTyped, EnsureType, ToTensord, EnsureChannelFirstD, RandSpatialCropd, Spacingd, SqueezeDimd


def main():
    path1 = "/home/sauroman/mia/data/angio/2/0002.DCM"
    path2 = "/home/sauroman/mia/data/angio/3/0003.DCM"

    #########Uncommenting this section will break the training#################
    #ds1 = pydicom.read_file(path1)
    #ds2 = pydicom.read_file(path2)

    #ds1.add_new((0x008, 0x005), 'CS', 'ISO_IR 100')
    #ds2.add_new((0x008, 0x005), 'CS', 'ISO_IR 100')
    #path1 = 'img1.dcm'
    #path2 = 'img2.dcm'
    #ds1.save_as(path1)
    #ds2.save_as(path2)
    ############################################################################
    images = [
        path1,
        path2
    ]

    labels = np.array([0, 1], dtype=np.int64)
    train_files = [{"img": img, "label": label} for img, label in zip(images, labels)]

    # Define transforms for image
    train_transforms = Compose(
        [
            LoadImaged(keys=["img"]),
            EnsureChannelFirstD(keys=["img"]),
            Resized(keys=["img"], spatial_size=(48, 48, 48)),
           # SqueezeDimd(keys=["img"], dim=-1),
            ToTensord(keys=["img"])
        ]
    )
    # Define dataset, data loader
    check_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    check_loader = DataLoader(check_ds, batch_size=2, num_workers=4, pin_memory=torch.cuda.is_available())
    check_data = monai.utils.misc.first(check_loader)
    print(check_data["img"].shape, check_data["label"])

    # create a training data loader
    train_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=4, pin_memory=torch.cuda.is_available())

    # Create DenseNet121, CrossEntropyLoss and Adam optimizer
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = monai.networks.nets.DenseNet121(spatial_dims=3, in_channels=1, out_channels=2).to(device)
    loss_function = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), 1e-5)

    # start a typical PyTorch training
    for epoch in range(50):
        print("-" * 10)
        print(f"epoch {epoch + 1}/{50}")
        model.train()
        epoch_loss = 0
        step = 0
        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data["img"].to(device), batch_data["label"].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            epoch_len = len(train_ds) // train_loader.batch_size
            print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
        epoch_loss /= step
        print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")


if __name__ == "__main__":
    main()
    
```
   
   ###################################################################################################
   Running this gives:
    ##################################################################################################
    Exception has occurred: KeyError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)# Code
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sauroman/.pyenv/versions/3.8.3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <listcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
KeyError: '0008|0005'

**Comment by wyli** [comment] 2021-09-14 17:29
Thanks for the detailed report, I can replicate the issue. The root cause is that not all the items in the dataset have the same set of metadata keys, but the data loader tries to 'stack' the value of each metadata field respectively.

a few possible solutions:
- enhance `monai.data.utils.PadListDataCollate` to be robust to batch a set of heterogeneous metadata
- enhance the image loader to load designated set of metadata only
- add a transform to filter the metadata field

cc @Nic-Ma @rijobro @ericspod

**Comment by Nic-Ma** [comment] 2021-09-15 02:39
Hi @wyli ,

Thanks for your analysis, I will enhance the transform to filter items.

**Comment by Nic-Ma** [comment] 2021-09-15 14:15
Hi @ChristianEschen ,

The enhancement PR had been merged into dev branch, could you please help sync and try again?
You just need to add the `DeleteItemsd` transforms to delete the keys：
```py
DeleteItemsd(keys="img_meta_dict.0008\\|[0-9]", use_re=True)
```

Thanks.

**Comment by ChristianEschen** [comment] 2021-09-15 18:17
Hi @Nic-Ma 

Thank you for the response

Yes you can fix it like this.
I work with images from a lot of different sources, and with a wide variety of tags (keys).
So the data loader will continue to throw more key errors.
For example I also need to delete these keys:
```

DeleteItemsd(keys="img_meta_dict.0008\\|[0-9]", use_re=True),
DeleteItemsd(keys="img_meta_dict.0020\\|[0-9]", use_re=True),
DeleteItemsd(keys="img_meta_dict.0028\\|[0-9]", use_re=True)

```
So I think we need a more viable solution here.
Maybe we should focus the data loader to only focus on designated tags.

**Comment by Nic-Ma** [comment] 2021-09-15 23:15
Hi @ChristianEschen ,

Thanks for your feedback, we can try to also provide the transform to only `keep` some items instead of `delete` in future.

**Comment by ChristianEschen** [comment] 2021-11-11 12:36
I think this issue is not solved, or maybe it has been more relevant in monai 0.7.
I need to drop at least all these keys in order to start at training session.

![image](https://user-images.githubusercontent.com/19329210/141299122-2269fc6b-2899-4037-9fa5-4abcdf8a26ee.png)

**Comment by Nic-Ma** [comment] 2021-11-11 13:00
Hi @ChristianEschen ,

I think we already fixed it in MONAI v0.7, could you please help try it?

Thanks in advance.

**Comment by lianggecm** [comment] 2022-08-02 20:23
I'm experiencing this issue in version 0.9.1 (it was not there for 0.9.0).

**Closed** 2022-08-03 14:24 UTC
Labels: bug

**Comment by wyli** [comment] 2022-08-04 06:31
in the latest version (>0.9.1) LoadImage transforms accept additional parameters such as `LoadImaged(prune_meta_pattern="^0008")`
