### ISSUE TITLE
DenseVNet for Monai

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/MONAI#2159] opened 2021-05-07 20:34 UTC
Greetings,

Will you please consider implementing DenseVNet from NiftyNet over to Monai? 

Thank you

**Comment by Nic-Ma** [comment] 2021-05-11 14:37
Hi @wyli ,

Could you please help share some comments for this feature request about NiftyNet?

Thanks in advance.

**Comment by wyli** [comment] 2021-05-13 10:10
duplicate of https://github.com/Project-MONAI/MONAI/issues/90

**Closed by wyli** 2021-05-13 10:10 UTC
Labels: Feature request
