### ISSUE TITLE
RandShiftIntensityd error: 'mtrand.RandomState' object has no attribute 'random'

### ISSUE THREAD

**Issue by bartmch** [Project-MONAI/MONAI#612] opened 2020-06-24 13:50 UTC
In my sequence of transforms:
```
train_transforms = Compose([
    LoadNiftid(["img","mask"], as_closest_canonical=True),
    AddChanneld(["img","mask"]),
    ScaleIntensityRanged("img", a_min=-1000, a_max=0, b_min=0., b_max=1., clip=True),
    CropForegroundd("img", 'mask',margin=0,select_fn=lambda x: x > 0),
    Resized(keys=["img"], spatial_size=(192, 192, 64)),
    RandShiftIntensityd(keys=["img"], offsets=1.0, prob=1.0),
])
```
everything works but the last tranforms "RandShiftIntensityd(keys=["img"], offsets=1.0, prob=1.0)" fails with:

> AttributeError: 'mtrand.RandomState' object has no attribute 'random'

Let me know if you need more context - Thanks!

**Comment by wyli** [comment] 2020-06-24 13:52
duplicate of https://github.com/Project-MONAI/MONAI/issues/390?

**Closed** 2020-06-29 21:22 UTC
Labels: question
