### ISSUE TITLE
Extending MONAI from medical to biomedical

### ISSUE THREAD

**Issue by jxchen01** [Project-MONAI/MONAI#4120] opened 2022-04-12 20:39 UTC
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/4119

<div type='discussions-op-text'>

<sup>Originally posted by **jxchen01** April 12, 2022</sup>
Hello All, When I look at the MONAI contribution guideline, I see that MONAI can only take contributions that are "medical-application specific". What if it is related to other microscopy images problem for biological research? How does everyone think about extending "medical-specific" to "biomedical-specific"? The underlying AI methods for "medical imaging" and "biomedical imaging" share a lot of similarity, but still have considerable difference. For example, the noise model in common light microscopes is very different from MR or CT. Another example is that it is common to see very 3D microscopy images have much more anisotropic dimensions than medical data. Also, the IO packages are different for bio data and for medical data. 

My group has been using MONAI for quite a while, but mostly using the models and loss functions. Re-building something new for the microscopy imaging community is too expensive and mostly re-invent the wheels. I can see that there is a huge potential to easily extend MONAI to support not only medical-specific applications, but general biomedical-specific applications. This will create a huge value for the microscopy / bio imaging community. 

As soon as there is a green light, my group would definitely wants to contribute to this bio imaging effort for MONAI. 

Best,
Jianxu Chen </div>

**Comment by wyli** [comment] 2022-04-13 09:41
Closing this as duplicate of https://github.com/Project-MONAI/MONAI/discussions/4119, we'll create new tickets once there are implementation plans.

**Closed by wyli** 2022-04-13 09:41 UTC
