### ISSUE TITLE
Why the data shape are different through transform "spacingd.

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5935] opened 2023-02-03 13:14 UTC
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/5934

<div type='discussions-op-text'>

<sup>Originally posted by **xxsxxsxxs666** February  3, 2023</sup>

![1675428782920](https://user-images.githubusercontent.com/61532031/216608306-d48a11ff-d351-47a3-af81-ffd5f01b98c9.jpg)

    val_transforms = Compose(
        [
            LoadImaged(keys=["image", "label"]),
            EnsureChannelFirstd(keys=["image", "label"]),
            ScaleIntensityRanged(
                keys=["image"], a_min=-57, a_max=400,
                b_min=0.0, b_max=1.0, clip=True,
            ),
            CropForegroundd(keys=["image", "label"], source_key="image"),  # default: value>0
            Orientationd(keys=["image", "label"], axcodes="RAI"),
            Spacingd(keys=["image", "label"], pixdim=(
                0.35, 0.35, 0.5), mode=("bilinear", "nearest")),  # Now only Sequential_str, How to add spline
        ]
    )

The shape and metadata are the same between image and label
![image](https://user-images.githubusercontent.com/61532031/216610903-9b586e06-0dd5-4cb4-85d8-05904146b159.png)

this problem only happen when I use cachedataset. Nothing went wrong when I use normal dataset. </div>

**Comment by wyli** [comment] 2023-02-06 09:39
thanks @xxsxxsxxs666 for reporting the issue, while I think the shape inconsistency could be addressed by using the `EnsureSameShaped` transform
https://github.com/Project-MONAI/MONAI/blob/f9842c0dda70714c826eeb8b12bbf93d987a0584/monai/apps/auto3dseg/transforms.py#L25-L32

I'm still not sure why this only happens with cacachedatset. Could you please share that test data if possible? I'm trying to reproduce the issue

**Comment by xxsxxsxxs666** [comment] 2023-02-07 03:47
Thanks for reply. It's very wierd that this problem only happen during training state, I can't recurrent that fault only using val dataset. But I still find something strange that shape of&nbsp;AI07_0012_01_B_diast_0.25mm.nii.gz after transform varies when the dataset's order is different. Sometime the shape is 639, but other times 640.Test code and data are in attachment.


19&nbsp;熊小松
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Project-MONAI/MONAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 下午5:39
***@***.***&gt;;
抄送:&nbsp;"19 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Project-MONAI/MONAI] Why the data shape are different through transform "spacingd. (Issue #5935)





 
thanks @xxsxxsxxs666 for reporting the issue, while I think the shape inconsistency could be addressed by using the EnsureSameShaped transform
 https://github.com/Project-MONAI/MONAI/blob/f9842c0dda70714c826eeb8b12bbf93d987a0584/monai/apps/auto3dseg/transforms.py#L25-L32
 
I'm still not sure why this only happens with cacachedatset. Could you please share that test data if possible? I'm trying to reproduce the issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

problem.7z (907.87M, 2023年03月09日 11:01 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5a613130c24221a4ae1ff2764766514c070406530552075548535508074b575001041c095052524e045707035251075407020101616c6313170e535c040b4d541f610c&code=ea10afcc

**Comment by wyli** [comment] 2023-02-07 21:51
thanks for the details @xxsxxsxxs666, I'm able to reproduce the issue and submitting a pull request https://github.com/Project-MONAI/MONAI/pull/5950 to fix it. 

The issue was with one of the images pixdim 0.346909 which was close to the target 0.35, the spacing transform correctly skipped the resampling but there's a buggy side-effect of assigning `self.pixdim` to 0.346909. the assignment was not thread-safe and when used with the cachedataset, it'll show some random behaviours, but your script narrowed it down, thanks!

**Closed** 2023-02-08 10:57 UTC
Labels: bug
