### ISSUE TITLE
WSI Reader (CuCIM): No option to specify GPU while reading region

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAI#4399] opened 2022-05-30 15:56 UTC
https://github.com/Project-MONAI/MONAI/blob/2c78bb0c5b8223ad4ff420d11821027871393c30/monai/data/wsi_reader.py#L453

Currently it only returns numpy and we like to have Numpy or Torch Tensor.. 
https://github.com/rapidsai/cucim/blob/branch-22.06/cpp/include/cucim/cuimage.h#L189

CuCIM supports device parameter `img.read_region(device='cuda', location=location)`

This should avoid unnecessary copies between GPU and CPU

**Comment by drbeh** [comment] 2022-05-31 21:25
Thank you very much @SachidanandAlle for making this feature request. I confirmed with cucim developers that currently the device is not supported in cucim (although the argument is there): https://docs.rapids.ai/api/cucim/nightly/api.html#cucim.clara.CuImage.read_region

Anyways, you should use `ToTensor` transform if you want torch.Tensor, even after cucim support cuda device in read_region because it will return cupy array.

I will close this issue until cucim support the device. There might be other changes too.

**Closed by drbeh** 2022-05-31 21:25 UTC
Labels: Feature request, Digital Pathology

**Comment by SachidanandAlle** [comment] 2022-05-31 23:07
In that case, until we have GPU to GPU mapping through cucim backend, this is less useful for optimizing load performance for image/regions.  will wait until GPU load is available.  thanks for checking on this..
