### ISSUE TITLE
MedNIST tutorial NotADirectoryError

### ISSUE THREAD

**Issue by lyshc** [Project-MONAI/MONAI#302] opened 2020-04-24 11:19 UTC
**Describe the bug**

NotADirectoryError: [Errno 20] Not a directory: './MedNIST/README.md' 
The error is in this tutorial: https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_tutorial.ipynb 

**To Reproduce**

1. Go to the mednist_tutorial.ipynb and run code blocks 1-4. Error is for this line in block 4:

```
imageFiles = [[os.path.join(dataDir, classNames[i], x) for x in os.listdir(os.path.join(dataDir, classNames[i]))]
              for i in range(numClass)]
```

**Environment (please complete the following information):**

 - OS: Linux version 4.19.104+ (using Google Colab)
 - Python version: 3.6.9
 - MONAI version [e.g. git commit hash]: 0.1.0

**Additional context**

Managed to fix error with replacing *classNames* variable also in block 4 with the following: 
`classNames = sorted([x for x in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir, x))])`

**Comment by Nic-Ma** [comment] 2020-04-24 11:57
Hi @lyshc ,

Thanks very much for your bug report!
This issue was caused by an update on the dataset file in the storage server.
And I already fixed in PR #301 
Thanks.

**Closed** 2020-04-24 12:15 UTC
