### ISSUE TITLE
Error with tensor size using ArrayDataset, but not with CacheDataset?

### ISSUE THREAD

**Issue by jillianlee** [Project-MONAI/MONAI#829] opened 2020-07-30 04:02 UTC
Hello,

I'm trying to use `ArrayDataset` to train a UNet with a single channeled image. I have my own data augmentation procedure that passes array data of size (160, 160) to `ArrayDataset`. I use the only the minimum transforms as follows:
```
transforms = Compose([
    AddChannel(),
    ToTensor()
    ])
```
After running through the data loader, I get a tensor of size (1, 160, 160).

 I then try and use a UNet with configurations 
`model = monai.networks.nets.UNet(dimensions=2, in_channels=1, out_channels=1, channels=(16, 32, 64), strides=(2, 2), num_res_units=2, norm=Norm.BATCH).to(device)`

This throws the following error:
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [1, 160, 160] instead`

I had previously been able to train a UNet with these configurations with a `CacheDataset` structure, reading directly from the Nifti files and applying the following transforms:
```
train_transforms = Compose([
    LoadNiftid(keys=['image', 'label']),
    AddChanneld(keys=['image', 'label']),
    Spacingd(keys=['image', 'label'], pixdim=(1.5, 1.5, 2.), mode=('bilinear', 'nearest')),
    Orientationd(keys=['image', 'label'], axcodes='RAS'),
    Resized(keys=['image'], spatial_size = (160, 160, 72)),
    Resized(keys=['label'], spatial_size = (160, 160, 72)),
    RandSpatialCropSamplesd(keys=['image', 'label'], roi_size=[160, 160, 1], num_samples = 72, random_center = True, random_size = False),
    SqueezeDimd(keys=['image', 'label'], dim=-1),
    ToNumpyd(keys=['image', 'label'])
])
```
The shape of the image tensor output from these transforms is (160, 160).

Is the size of the output tensor the issue? Should I do an external squeeze or is there something else I'm doing wrong in setting up the ArrayDataset? 

Thanks,
Jillian

**Comment by Nic-Ma** [comment] 2020-07-30 14:58
Hi @jillianlee ,

Thanks for your interest here and experiments.
I think the expected shape of output data from DataLoader is `[B, C, H, W]`, but seems your shape is `[C, H, W]`.
May I know what's your batch size?

Thanks.

**Comment by jillianlee** [comment] 2020-07-30 16:12
Hi @Nic-Ma 

The batch_size is set to 2 or 1 in both experiments for training and validation respectively.

Thanks,
Jillian

**Comment by Nic-Ma** [comment] 2020-08-03 13:52
OK, I can't guess the root cause now, could you please help paste your program here?
I don't know why the data is not batched after DataLoader.

Thanks.

**Comment by jillianlee** [comment] 2020-08-03 23:38
Hi @Nic-Ma 

Here is my code below:

```
def build_u_net_model(train, trainlab, val, vallab, test, testlab, hparams):
    monai.config.print_config()
    set_determinism(seed=0)
    tempdir = tempfile.mkdtemp()
    
    batch_size = hparams.batch_size
    num_epochs = hparams.num_epochs
    lr = hparams.lr
    
    transforms = Compose([
    AddChannel(),
    ToTensor()
    ])
    
    train_data = monai.data.ArrayDataset(img = train, img_transform = transforms, seg = trainlab, seg_transform = transforms)
    train_loader = monai.data.DataLoader(train_data, batch_size=2, shuffle=True, num_workers=0, multiprocessing_context = None)
    

    val_data = monai.data.ArrayDataset(img = val, img_transform = transforms, seg = vallab, seg_transform = transforms)
    val_loader = monai.data.DataLoader(val_data, batch_size=1, shuffle=True, num_workers=0, multiprocessing_context = None)

    test_data = monai.data.ArrayDataset(img = test, img_transform = transforms, seg = testlab, seg_transform = transforms)
    test_loader = monai.data.DataLoader(test_data, batch_size=1, shuffle=True, num_workers=0, multiprocessing_context = None)
    
    torch.cuda.set_device(0)    
    device = torch.device('cuda:0')
    model = monai.networks.nets.UNet(dimensions=2, in_channels=1, out_channels=1, channels=(16, 32, 64),
                                      strides=(2, 2), num_res_units=2, norm=Norm.BATCH).to(device)
    
    loss_function = monai.losses.DiceLoss(to_onehot_y=True, sigmoid=True)
    optimizer = torch.optim.Adam(model.parameters(), lr)
    
    # TRAINING
    val_interval = 2
    best_metric = -1
    best_metric_epoch = -1
    epoch_loss_values = list()
    metric_values = list()

    for epoch in range(num_epochs):
        print("-" * 10)
        print(f"epoch {epoch + 1}/{20}")
        model.train()
        epoch_loss = 0
        step = 0
        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data[0].to(device), batch_data[1].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            epoch_len = len(train_data) // train_loader.batch_size
            print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
        epoch_loss /= step
        epoch_loss_values.append(epoch_loss)
        print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")

        if (epoch + 1) % val_interval == 0:
            model.eval()
            with torch.no_grad():
                metric_sum = 0.0
                metric_count = 0
                val_images = None
                val_labels = None
                val_outputs = None
                for val_data in val_loader:
                    val_images, val_labels = val_data[0].to(device), val_data[1].to(device)
                    roi_size = (96, 96, 96)
                    sw_batch_size = 4
                    val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, model)
                    value = DiceMetric(y_pred=val_outputs, y=val_labels)
                    metric_count += len(value)
                    metric_sum += value.item() * len(value)
                metric = metric_sum / metric_count
                metric_values.append(metric)
                if metric > best_metric:
                    best_metric = metric
                    best_metric_epoch = epoch + 1
                    torch.save(model.state_dict(), "best_metric_model.pth")
                    print("saved new best metric model")
                print(
                    "current epoch: {} current mean dice: {:.4f} best mean dice: {:.4f} at epoch {}".format(
                        epoch + 1, metric, best_metric, best_metric_epoch
                    )
                )
    shutil.rmtree(tempdir)
    print(f"train completed, best_metric: {best_metric:.4f} at epoch: {best_metric_epoch}")
    train_acc = best_metric
```

I think I may be confused about the intended input for ArrayDataset. Your posted examples using array data first export the data to Nifti files and then read them back in using a NiftiDataset. In the snippets in your docs for ArrayDataset, the input images seems to be a filename list of array data. 

In my code here, I pass `train` which is a list of image arrays. All my input data is formatted in this way.
```
len(train) = 3600
train[i].shape = (160, 160)
```
Here is the traceback:

```
  File "C:\Users\iBest\Documents\Jillian\Documents\BO-Aug-master\BraTS\select\bo_train_brats.py", line 125, in run_model
    train_acc, val_acc, test_accuracy = build_u_net_model(train_images, train_labels, val_images, val_labels, test_images, test_labels, hparams)
  File "C:\Users\iBest\Documents\Jillian\Documents\BO-Aug-master\BraTS\select\u_net.py", line 119, in build_u_net_model
    outputs = model(inputs)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\monai\networks\nets\unet.py", line 137, in forward
    x = self.model(x)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\monai\networks\blocks\convolutions.py", line 209, in forward
    res = self.residual(x)  # create the additive residual from x
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\iBest\.conda\envs\data_aug\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [1, 160, 160] instead
```
Does ArrayDataset accept this kind of format?

Thank you for your time and help,
Jillian

**Comment by Nic-Ma** [comment] 2020-08-04 00:40
Hi @jillianlee ,

Could you please help check the data shape of `batch_data[0]` from `for batch_data in train_loader`?
I think you need to add several print logs to find out why the output data of DataLoader is not [B, C, H, W].

Thanks.

**Comment by jillianlee** [comment] 2020-08-04 02:00
Hi @Nic-Ma,

Both `batch_data[0]` and 'batch_data[1]` are size (1, 160, 160).

Additionally `train_loader.dataset[0][0]` is also size (1, 160, 160).

Best,
Jillian

**Comment by wyli** [comment] 2020-08-06 11:27
Hi both, it is indeed an issue (at least a documentation issue) just checked that in the previous example, changing `monai.data.Dataloader` to `torch.utils.data.DataLoader` then everything works fine.

I used these test cases:
```python
build_u_net_model(train=[np.zeros((160, 160))] * 3, trainlab=[np.zeros((160, 160))] * 3, ...)
```

**Comment by wyli** [comment] 2020-08-06 11:37
@Nic-Ma 
```py
import torch
import monai
from monai.utils.misc import set_determinism
from monai.transforms import AddChannel, Compose, ToTensor


def build_u_net_model(train, trainlab):
    monai.config.print_config()
    set_determinism(seed=0)

    batch_size = 2

    transforms = Compose([AddChannel(), ToTensor()])

    train_data = monai.data.ArrayDataset(img=train, img_transform=transforms, seg=trainlab, seg_transform=transforms)
    train_loader = monai.data.DataLoader(
        train_data, batch_size=2, shuffle=True, num_workers=0, multiprocessing_context=None
    )
    train_loader_1 = torch.utils.data.DataLoader(
        train_data, batch_size=2, shuffle=True, num_workers=0, multiprocessing_context=None
    )
    for x in train_loader:
        print(x[0].shape)
    for x in train_loader_1:
        print(x[0].shape)

import numpy as np
train = [np.zeros((160, 160))] * 3
trainlab = [np.ones((160, 160))] * 3
build_u_net_model(train, trainlab)
```

**Comment by Nic-Ma** [comment] 2020-08-06 12:25
Thanks for your help @wyli !
I will try to verify and fix soon.

**Comment by Nic-Ma** [comment] 2020-08-06 14:40
Hi @jillianlee ,

Sorry for the bug, I committed PR #865 to fix this issue.
Thanks.

**Closed** 2020-08-06 15:09 UTC
Labels: bug, question
