### ISSUE TITLE
`test_scale_intensity_range_percentiles` error

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3620] opened 2022-01-09 16:35 UTC
**Describe the bug**
a frequent error for the recent unit testing, e.g. the log here: https://github.com/Project-MONAI/MONAI/actions/runs/1674183498
```
======================================================================
FAIL: test_channel_wise (tests.test_scale_intensity_range_percentiles.TestScaleIntensityRangePercentiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_scale_intensity_range_percentiles.py", line 86, in test_channel_wise
    assert_allclose(result, p(expected), rtol=1e-4)
  File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/utils.py", line 92, in assert_allclose
    np.testing.assert_allclose(actual, desired, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0

Mismatched elements: 496 / 8192 (6.05%)
Max absolute difference: 255.
Max relative difference: 1.008
 x: array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],...
 y: array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],...

----------------------------------------------------------------------
```

```
MONAI version: 0+unknown
Numpy version: 1.21.5
Pytorch version: 1.8.1+cu102
MONAI flags: HAS_EXT = True, USE_COMPILED = True
MONAI rev id: None

Optional dependencies:
Pytorch Ignite version: 0.4.7
Nibabel version: 3.2.1
scikit-image version: 0.19.1
Pillow version: 9.0.0
Tensorboard version: 2.7.0
gdown version: 4.2.0
TorchVision version: 0.9.1+cu102
tqdm version: 4.62.3
lmdb version: 1.3.0
psutil version: 5.9.0
pandas version: 1.3.5
einops version: 0.3.2
transformers version: 4.15.0
mlflow version: 1.22.0
```

**Comment by Nic-Ma** [comment] 2022-01-09 23:20
Hi @wyli ,

I saw a similar issue in this test file before, and fixed with the `dtype` arg, so I think this `channel_wise` error may also related to it, can I submit a draft PR and let's run many times to test it on Blossom?

Thanks.

**Comment by Nic-Ma** [comment] 2022-01-10 03:58
Hi @wyli ,

I think the root cause is same as what I fixed before: when `channel_wise` and the `dtype` is different from input `img`, the transform doesn't use `dtype` as data type as final return data type. It can reproduce by:
```
>>> import numpy as np
>>> 
>>> a = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
>>> 
>>> b = np.array([100, 200], dtype=np.uint8)
>>> 
>>> a[1] = b
>>> 
>>> print(a)
[[  1.   2.]
 [100. 200.]]
>>> 
>>> print(a.dtype)
float32
```
Submitted draft PR #3625 to test and fix it to be consistent with existing solution:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/intensity/array.py#L450

Thanks.

**Comment by wyli** [comment] 2022-01-20 01:05
this is still an issue
```py
======================================================================
FAIL: test_channel_wise (tests.test_scale_intensity_range_percentilesd.TestScaleIntensityRangePercentilesd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/MONAI/MONAI/tests/test_scale_intensity_range_percentilesd.py", line 95, in test_channel_wise
    assert_allclose(scaler(data)["img"], p(expected), rtol=1e-4)
  File "/home/runner/work/MONAI/MONAI/tests/utils.py", line 93, in assert_allclose
    np.testing.assert_allclose(actual, desired, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0

Mismatched elements: 853 / 8192 (10.4%)
Max absolute difference: 117
Max relative difference: 0.86029412
 x: array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],...
 y: array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],...

----------------------------------------------------------------------
```

```
MONAI version: 0+untagged.1.g32516e7
Numpy version: 1.22.1
Pytorch version: 1.6.0
```

**Comment by wyli** [comment] 2022-05-13 11:05
this is an issue recently happenning randomly (with pytorch 22.04)

```
[2022-05-13T00:03:17.379Z] ======================================================================
[2022-05-13T00:03:17.379Z] FAIL: test_channel_wise (tests.test_scale_intensity_range_percentiles.TestScaleIntensityRangePercentiles)
[2022-05-13T00:03:17.379Z] ----------------------------------------------------------------------
[2022-05-13T00:03:17.379Z] Traceback (most recent call last):
[2022-05-13T00:03:17.379Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_scale_intensity_range_percentiles.py", line 86, in test_channel_wise
[2022-05-13T00:03:17.379Z]     assert_allclose(result, p(expected), rtol=1e-4)
[2022-05-13T00:03:17.379Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 107, in assert_allclose
[2022-05-13T00:03:17.379Z]     np.testing.assert_allclose(actual, desired, *args, **kwargs)
[2022-05-13T00:03:17.379Z]   File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
[2022-05-13T00:03:17.379Z]     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
[2022-05-13T00:03:17.379Z]   File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
[2022-05-13T00:03:17.379Z]     raise AssertionError(msg)
[2022-05-13T00:03:17.379Z] AssertionError: 
[2022-05-13T00:03:17.379Z] Not equal to tolerance rtol=0.0001, atol=0
[2022-05-13T00:03:17.379Z] 
[2022-05-13T00:03:17.379Z] Mismatched elements: 1203 / 24576 (4.9%)
[2022-05-13T00:03:17.379Z] Max absolute difference: 1
[2022-05-13T00:03:17.379Z] Max relative difference: 0.00529101
[2022-05-13T00:03:17.379Z]  x: array([[[[0, 0, 0, ..., 0, 0, 0],
[2022-05-13T00:03:17.379Z]          [0, 0, 0, ..., 0, 0, 0],
[2022-05-13T00:03:17.379Z]          [0, 0, 0, ..., 0, 0, 0],...
[2022-05-13T00:03:17.379Z]  y: array([[[[0, 0, 0, ..., 0, 0, 0],
[2022-05-13T00:03:17.379Z]          [0, 0, 0, ..., 0, 0, 0],
[2022-05-13T00:03:17.379Z]          [0, 0, 0, ..., 0, 0, 0],...
[2022-05-13T00:03:17.379Z] 
[2022-05-13T00:03:17.379Z] ----------------------------------------------------------------------
```

**Closed** 2022-07-09 13:12 UTC
Labels: bug
